In [1]:
import pandas as pd
df = pd.read_table('datasets/SMSSpamCollection',
                   sep='\t', 
                   header=None, 
                   names=['label', 'sms_message'])

df.head()

C:\Users\PARAMESH\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: read_table is deprecated, use read_csv instead.
  


label                                        sms_message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [2]:
df['label'] = df.label.map({'ham':0, 'spam':1})
print(df.shape)
df.head() 

(5572, 2)


label                                        sms_message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer()

In [4]:
print(count_vector)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)


In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['sms_message'], 
                                                    df['label'], 
                                                    random_state=1)

print('Number of rows in the total set: {}'.format(df.shape[0]))
print('Number of rows in the training set: {}'.format(X_train.shape[0]))
print('Number of rows in the test set: {}'.format(X_test.shape[0]))

Number of rows in the total set: 5572
Number of rows in the training set: 4179
Number of rows in the test set: 1393


In [7]:
count_vector = CountVectorizer()
training_data = count_vector.fit_transform(X_train)
testing_data = count_vector.transform(X_test)

In [8]:
from sklearn.naive_bayes import MultinomialNB
naive_bayes = MultinomialNB()
naive_bayes.fit(training_data, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [10]:
predictions = naive_bayes.predict(testing_data)
predictions

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [12]:
x=['Dear Paramesha MR,Greetings from Company Etiquette Global corporation!! (www.etiquettepromotion.com) \
Your CV has been shortlisted for the role of Trainee Business Head. Desired candidature is as follows: \
Experience: 0-1 Years Earnings potential : Rs 20000/- to 45000/- Per Month ( During Training) Rs 10,00,000/- to 15,00,000/- PA (As Business Head - After Training) Job Location: Bangalore No. of Vacancies: 50 Position for Trainee Business Head Please directly walk-in for an interview to our office in Shantinagar ( In front of double road fly over ) as below mentioned date and time. Kindly call to the contact person in case any difficulty to find the address or any queries']

In [13]:
x=count_vector.transform(x)

In [14]:
predictions = naive_bayes.predict(x)
predictions

array([0], dtype=int64)

In [25]:
y=pd.read_csv('sms.txt',delimiter="\t")
y=count_vector.transform(y)
predictions = naive_bayes.predict(y)
predictions


array([1], dtype=int64)